### ISSUE TITLE
Multiple xml headers and <Account> tags in xml

### ISSUE THREAD

**Issue by jmgibson71** [StateArchivesOfNorthCarolina/DarcMailCLI#2]
**Source:** Test export from Nitin's outlook.
**Process:** readpst 

**Output:**
```xml
<xml version="1.0" encoding="UTF-8"?>
<Account xmlns="http://www.archives.ncdcr.gov/mail-account" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.history.ncdcr.gov/SHRAB/ar/emailpreservation/mail-account/mail-account.xsd">
	<GlobalId>nitin</GlobalId>
	<Folder>
		<Name>United States holidays</Name>
	</Folder>
	<?xml version="1.0" encoding="UTF-8"?>
	<Account xmlns="http://www.archives.ncdcr.gov/mail-account" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.history.ncdcr.gov/SHRAB/ar/emailpreservation/mail-account/mail-account.xsd">
		<GlobalId>nitin</GlobalId>
		<Folder>
			<Name>Calendar</Name>
		</Folder>
		<?xml version="1.0" encoding="UTF-8"?>
		<Account xmlns="http://www.archives.ncdcr.gov/mail-account" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.history.ncdcr.gov/SHRAB/ar/emailpreservation/mail-account/mail-account.xsd">
			<GlobalId>nitin</GlobalId>
			<Folder>
				<Name>Recipient Cache</Name>
			</Folder>
```

**Comment by jmgibson71** [comment]
This looks to be an issue with lines 226-237 in the `find_mbox_files` method.  DarcMailCLI does not expect anything other than email mboxes.  

**Short term fix**: use the `-t e` switch on the readpst command. This makes sure that readpst only exports emails and zero's out calendars, contacts, journals, or appointments.  The zero size file is caught at line 228.

**Long term fix**: Identify all possible non-email folders and content types and exclude them in the `find_mbox_files` method.

Holding open until decision made.

**Comment by nitaro** [comment]
Prefer long term solution at the least, but if we need to have contacts to build names entities, etc., then I'd also lean toward a solution that modifies [pst_to_mbox](https://github.com/StateArchivesOfNorthCarolina/tomes_tool/tree/master/pst_to_mbox) to shuffle the readpst output after the fact.
